//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGuiConsumoService.ServiceMantenedorMerma {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorMerma.WebServiceMantenedorMermaSoap")]
    public interface WebServiceMantenedorMermaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarMermaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarMermaService(CapaGuiConsumoService.ServiceMantenedorMerma.Merma merma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarMermaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarMermaService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionMermaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorMerma.Merma retornaPosicionMermaService(int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarMermaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorMerma.Merma buscarMermaService(string id_merma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarMermaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarMermaService(string id_merma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarMermaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarMermaService(CapaGuiConsumoService.ServiceMantenedorMerma.Merma merma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarMermaDetalleService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarMermaDetalleService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarMermaPorIdMermaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarMermaPorIdMermaService(string id_merma);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Merma : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_mermaField;
        
        private System.DateTime fechaField;
        
        private string motivoField;
        
        private string tipo_solicitudField;
        
        private string usuario_rutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_merma {
            get {
                return this.id_mermaField;
            }
            set {
                this.id_mermaField = value;
                this.RaisePropertyChanged("Id_merma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
                this.RaisePropertyChanged("Motivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Tipo_solicitud {
            get {
                return this.tipo_solicitudField;
            }
            set {
                this.tipo_solicitudField = value;
                this.RaisePropertyChanged("Tipo_solicitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Usuario_rut {
            get {
                return this.usuario_rutField;
            }
            set {
                this.usuario_rutField = value;
                this.RaisePropertyChanged("Usuario_rut");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorMermaSoapChannel : CapaGuiConsumoService.ServiceMantenedorMerma.WebServiceMantenedorMermaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorMermaSoapClient : System.ServiceModel.ClientBase<CapaGuiConsumoService.ServiceMantenedorMerma.WebServiceMantenedorMermaSoap>, CapaGuiConsumoService.ServiceMantenedorMerma.WebServiceMantenedorMermaSoap {
        
        public WebServiceMantenedorMermaSoapClient() {
        }
        
        public WebServiceMantenedorMermaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorMermaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorMermaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorMermaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarMermaService(CapaGuiConsumoService.ServiceMantenedorMerma.Merma merma) {
            base.Channel.insertarMermaService(merma);
        }
        
        public System.Data.DataSet retornarMermaService() {
            return base.Channel.retornarMermaService();
        }
        
        public CapaGuiConsumoService.ServiceMantenedorMerma.Merma retornaPosicionMermaService(int pos) {
            return base.Channel.retornaPosicionMermaService(pos);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorMerma.Merma buscarMermaService(string id_merma) {
            return base.Channel.buscarMermaService(id_merma);
        }
        
        public void eliminarMermaService(string id_merma) {
            base.Channel.eliminarMermaService(id_merma);
        }
        
        public void actualizarMermaService(CapaGuiConsumoService.ServiceMantenedorMerma.Merma merma) {
            base.Channel.actualizarMermaService(merma);
        }
        
        public System.Data.DataSet retornarMermaDetalleService() {
            return base.Channel.retornarMermaDetalleService();
        }
        
        public System.Data.DataSet retornarMermaPorIdMermaService(string id_merma) {
            return base.Channel.retornarMermaPorIdMermaService(id_merma);
        }
    }
}
