//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGuiConsumoService.ServiceMantenedorIngresoProducto {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorIngresoProducto.WebServiceMantenedorIngresoProductoSoap")]
    public interface WebServiceMantenedorIngresoProductoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarIngresoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarIngresoProductoService(CapaGuiConsumoService.ServiceMantenedorIngresoProducto.Ingreso_P ingreso_producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarIngresoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listarIngresoProductoService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarIngresoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarIngresoProductoService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarPorIdIngresoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscarPorIdIngresoService(string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionIngresoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorIngresoProducto.Ingreso_P retornaPosicionIngresoProductoService(int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIngresoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorIngresoProducto.Ingreso_P buscarIngresoProductoService(string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarIngresoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarIngresoProductoService(string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarIngresoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarIngresoProductoService(CapaGuiConsumoService.ServiceMantenedorIngresoProducto.Ingreso_P ingreso_producto);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ingreso_P : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_ingresoField;
        
        private System.DateTime fechaField;
        
        private string usuario_rutField;
        
        private string proveedor_rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_ingreso {
            get {
                return this.id_ingresoField;
            }
            set {
                this.id_ingresoField = value;
                this.RaisePropertyChanged("Id_ingreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Usuario_rut {
            get {
                return this.usuario_rutField;
            }
            set {
                this.usuario_rutField = value;
                this.RaisePropertyChanged("Usuario_rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Proveedor_rol {
            get {
                return this.proveedor_rolField;
            }
            set {
                this.proveedor_rolField = value;
                this.RaisePropertyChanged("Proveedor_rol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorIngresoProductoSoapChannel : CapaGuiConsumoService.ServiceMantenedorIngresoProducto.WebServiceMantenedorIngresoProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorIngresoProductoSoapClient : System.ServiceModel.ClientBase<CapaGuiConsumoService.ServiceMantenedorIngresoProducto.WebServiceMantenedorIngresoProductoSoap>, CapaGuiConsumoService.ServiceMantenedorIngresoProducto.WebServiceMantenedorIngresoProductoSoap {
        
        public WebServiceMantenedorIngresoProductoSoapClient() {
        }
        
        public WebServiceMantenedorIngresoProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorIngresoProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorIngresoProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorIngresoProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarIngresoProductoService(CapaGuiConsumoService.ServiceMantenedorIngresoProducto.Ingreso_P ingreso_producto) {
            base.Channel.insertarIngresoProductoService(ingreso_producto);
        }
        
        public System.Data.DataSet listarIngresoProductoService() {
            return base.Channel.listarIngresoProductoService();
        }
        
        public System.Data.DataSet retornarIngresoProductoService() {
            return base.Channel.retornarIngresoProductoService();
        }
        
        public System.Data.DataSet buscarPorIdIngresoService(string id_ingreso) {
            return base.Channel.buscarPorIdIngresoService(id_ingreso);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorIngresoProducto.Ingreso_P retornaPosicionIngresoProductoService(int pos) {
            return base.Channel.retornaPosicionIngresoProductoService(pos);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorIngresoProducto.Ingreso_P buscarIngresoProductoService(string id_ingreso) {
            return base.Channel.buscarIngresoProductoService(id_ingreso);
        }
        
        public void eliminarIngresoProductoService(string id_ingreso) {
            base.Channel.eliminarIngresoProductoService(id_ingreso);
        }
        
        public void actualizarIngresoProductoService(CapaGuiConsumoService.ServiceMantenedorIngresoProducto.Ingreso_P ingreso_producto) {
            base.Channel.actualizarIngresoProductoService(ingreso_producto);
        }
    }
}
