//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGuiConsumoService.ServiceMantenedorUbicacion {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorUbicacion.WebServiceUbicacionSoap")]
    public interface WebServiceUbicacionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarUbicacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarUbicacionService(CapaGuiConsumoService.ServiceMantenedorUbicacion.Ubicacion ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarUbicacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarUbicacionService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionUbicacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorUbicacion.Ubicacion retornaPosicionUbicacionService(int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarUbicacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorUbicacion.Ubicacion buscarUbicacionService(string id_ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarUbicacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarUbicacionService(string id_ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarUbicacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarUbicacionService(CapaGuiConsumoService.ServiceMantenedorUbicacion.Ubicacion ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarUbicacionCodigoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscarUbicacionCodigoProductoService(string codigo_producto);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ubicacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_ubicacionField;
        
        private string nombre_ubicacionField;
        
        private System.DateTime fecha_ingreso_ubicacionField;
        
        private string producto_codigoField;
        
        private int cantidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_ubicacion {
            get {
                return this.id_ubicacionField;
            }
            set {
                this.id_ubicacionField = value;
                this.RaisePropertyChanged("Id_ubicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre_ubicacion {
            get {
                return this.nombre_ubicacionField;
            }
            set {
                this.nombre_ubicacionField = value;
                this.RaisePropertyChanged("Nombre_ubicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Fecha_ingreso_ubicacion {
            get {
                return this.fecha_ingreso_ubicacionField;
            }
            set {
                this.fecha_ingreso_ubicacionField = value;
                this.RaisePropertyChanged("Fecha_ingreso_ubicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Producto_codigo {
            get {
                return this.producto_codigoField;
            }
            set {
                this.producto_codigoField = value;
                this.RaisePropertyChanged("Producto_codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUbicacionSoapChannel : CapaGuiConsumoService.ServiceMantenedorUbicacion.WebServiceUbicacionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUbicacionSoapClient : System.ServiceModel.ClientBase<CapaGuiConsumoService.ServiceMantenedorUbicacion.WebServiceUbicacionSoap>, CapaGuiConsumoService.ServiceMantenedorUbicacion.WebServiceUbicacionSoap {
        
        public WebServiceUbicacionSoapClient() {
        }
        
        public WebServiceUbicacionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUbicacionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUbicacionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUbicacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarUbicacionService(CapaGuiConsumoService.ServiceMantenedorUbicacion.Ubicacion ubicacion) {
            base.Channel.insertarUbicacionService(ubicacion);
        }
        
        public System.Data.DataSet retornarUbicacionService() {
            return base.Channel.retornarUbicacionService();
        }
        
        public CapaGuiConsumoService.ServiceMantenedorUbicacion.Ubicacion retornaPosicionUbicacionService(int pos) {
            return base.Channel.retornaPosicionUbicacionService(pos);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorUbicacion.Ubicacion buscarUbicacionService(string id_ubicacion) {
            return base.Channel.buscarUbicacionService(id_ubicacion);
        }
        
        public void eliminarUbicacionService(string id_ubicacion) {
            base.Channel.eliminarUbicacionService(id_ubicacion);
        }
        
        public void actualizarUbicacionService(CapaGuiConsumoService.ServiceMantenedorUbicacion.Ubicacion ubicacion) {
            base.Channel.actualizarUbicacionService(ubicacion);
        }
        
        public System.Data.DataSet buscarUbicacionCodigoProductoService(string codigo_producto) {
            return base.Channel.buscarUbicacionCodigoProductoService(codigo_producto);
        }
    }
}
