//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGuiConsumoService.ServiceMantenedorProducto {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorProducto.WebServiceMantenedorProductoSoap")]
    public interface WebServiceMantenedorProductoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarProductoService(CapaGuiConsumoService.ServiceMantenedorProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarProductoService(string id_marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorProducto.Producto retornaPosicionProductoService(int pos, string id_marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorProducto.Producto buscarProductoService(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarProductoService(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarProductoService(CapaGuiConsumoService.ServiceMantenedorProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarCodigoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscarCodigoProductoService(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdMarcaProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorProducto.Producto buscarIdMarcaProductoService(string id_marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarTotalProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarTotalProductoService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarStockProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarStockProductoService(string codigo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descripcionField;
        
        private int precio_unitarioField;
        
        private int cantidad_totalField;
        
        private string marca_id_marcaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Precio_unitario {
            get {
                return this.precio_unitarioField;
            }
            set {
                this.precio_unitarioField = value;
                this.RaisePropertyChanged("Precio_unitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Cantidad_total {
            get {
                return this.cantidad_totalField;
            }
            set {
                this.cantidad_totalField = value;
                this.RaisePropertyChanged("Cantidad_total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Marca_id_marca {
            get {
                return this.marca_id_marcaField;
            }
            set {
                this.marca_id_marcaField = value;
                this.RaisePropertyChanged("Marca_id_marca");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorProductoSoapChannel : CapaGuiConsumoService.ServiceMantenedorProducto.WebServiceMantenedorProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorProductoSoapClient : System.ServiceModel.ClientBase<CapaGuiConsumoService.ServiceMantenedorProducto.WebServiceMantenedorProductoSoap>, CapaGuiConsumoService.ServiceMantenedorProducto.WebServiceMantenedorProductoSoap {
        
        public WebServiceMantenedorProductoSoapClient() {
        }
        
        public WebServiceMantenedorProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarProductoService(CapaGuiConsumoService.ServiceMantenedorProducto.Producto producto) {
            base.Channel.insertarProductoService(producto);
        }
        
        public System.Data.DataSet retornarProductoService(string id_marca) {
            return base.Channel.retornarProductoService(id_marca);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorProducto.Producto retornaPosicionProductoService(int pos, string id_marca) {
            return base.Channel.retornaPosicionProductoService(pos, id_marca);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorProducto.Producto buscarProductoService(string codigo) {
            return base.Channel.buscarProductoService(codigo);
        }
        
        public void eliminarProductoService(string codigo) {
            base.Channel.eliminarProductoService(codigo);
        }
        
        public void actualizarProductoService(CapaGuiConsumoService.ServiceMantenedorProducto.Producto producto) {
            base.Channel.actualizarProductoService(producto);
        }
        
        public System.Data.DataSet buscarCodigoProductoService(string codigo) {
            return base.Channel.buscarCodigoProductoService(codigo);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorProducto.Producto buscarIdMarcaProductoService(string id_marca) {
            return base.Channel.buscarIdMarcaProductoService(id_marca);
        }
        
        public System.Data.DataSet retornarTotalProductoService() {
            return base.Channel.retornarTotalProductoService();
        }
        
        public System.Data.DataSet retornarStockProductoService(string codigo) {
            return base.Channel.retornarStockProductoService(codigo);
        }
    }
}
