//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGuiConsumoService.ServiceMantenedorDetalleMerma {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorDetalleMerma.WebServiceMantenedorDetMermaSoap")]
    public interface WebServiceMantenedorDetMermaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarDetalleMermaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarDetalleMermaService(CapaGuiConsumoService.ServiceMantenedorDetalleMerma.Det_Merma detalle_merma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarDetalleMermaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarDetalleMermaService(string id_merma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionDetalleMermaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorDetalleMerma.Det_Merma retornaPosicionDetalleMermaService(int pos, string id_merma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarDetalleMermaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorDetalleMerma.Det_Merma buscarDetalleMermaService(string id_det_merma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDetalleMermaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarDetalleMermaService(string id_det_merma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarDetalleMermaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarDetalleMermaService(CapaGuiConsumoService.ServiceMantenedorDetalleMerma.Det_Merma detalle_merma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarDetallePorIdMermaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorDetalleMerma.Det_Merma buscarDetallePorIdMermaService(string id_merma);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Det_Merma : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_det_mermaField;
        
        private int cantidadField;
        
        private string producto_codigoField;
        
        private int valor_totalField;
        
        private string merma_id_mermaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_det_merma {
            get {
                return this.id_det_mermaField;
            }
            set {
                this.id_det_mermaField = value;
                this.RaisePropertyChanged("Id_det_merma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Producto_codigo {
            get {
                return this.producto_codigoField;
            }
            set {
                this.producto_codigoField = value;
                this.RaisePropertyChanged("Producto_codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Valor_total {
            get {
                return this.valor_totalField;
            }
            set {
                this.valor_totalField = value;
                this.RaisePropertyChanged("Valor_total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Merma_id_merma {
            get {
                return this.merma_id_mermaField;
            }
            set {
                this.merma_id_mermaField = value;
                this.RaisePropertyChanged("Merma_id_merma");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorDetMermaSoapChannel : CapaGuiConsumoService.ServiceMantenedorDetalleMerma.WebServiceMantenedorDetMermaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorDetMermaSoapClient : System.ServiceModel.ClientBase<CapaGuiConsumoService.ServiceMantenedorDetalleMerma.WebServiceMantenedorDetMermaSoap>, CapaGuiConsumoService.ServiceMantenedorDetalleMerma.WebServiceMantenedorDetMermaSoap {
        
        public WebServiceMantenedorDetMermaSoapClient() {
        }
        
        public WebServiceMantenedorDetMermaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorDetMermaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorDetMermaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorDetMermaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarDetalleMermaService(CapaGuiConsumoService.ServiceMantenedorDetalleMerma.Det_Merma detalle_merma) {
            base.Channel.insertarDetalleMermaService(detalle_merma);
        }
        
        public System.Data.DataSet retornarDetalleMermaService(string id_merma) {
            return base.Channel.retornarDetalleMermaService(id_merma);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorDetalleMerma.Det_Merma retornaPosicionDetalleMermaService(int pos, string id_merma) {
            return base.Channel.retornaPosicionDetalleMermaService(pos, id_merma);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorDetalleMerma.Det_Merma buscarDetalleMermaService(string id_det_merma) {
            return base.Channel.buscarDetalleMermaService(id_det_merma);
        }
        
        public void eliminarDetalleMermaService(string id_det_merma) {
            base.Channel.eliminarDetalleMermaService(id_det_merma);
        }
        
        public void actualizarDetalleMermaService(CapaGuiConsumoService.ServiceMantenedorDetalleMerma.Det_Merma detalle_merma) {
            base.Channel.actualizarDetalleMermaService(detalle_merma);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorDetalleMerma.Det_Merma buscarDetallePorIdMermaService(string id_merma) {
            return base.Channel.buscarDetallePorIdMermaService(id_merma);
        }
    }
}
