//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGuiConsumoService.ServiceMantenedorCliente {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorCliente.WebServiceMantenedorClienteSoap")]
    public interface WebServiceMantenedorClienteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarClienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarClienteService(CapaGuiConsumoService.ServiceMantenedorCliente.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarClienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarClienteService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionClienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorCliente.Cliente retornaPosicionClienteService(int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarClienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorCliente.Cliente buscarClienteService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarClienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarClienteService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarClienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarClienteService(CapaGuiConsumoService.ServiceMantenedorCliente.Cliente cliente);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorClienteSoapChannel : CapaGuiConsumoService.ServiceMantenedorCliente.WebServiceMantenedorClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorClienteSoapClient : System.ServiceModel.ClientBase<CapaGuiConsumoService.ServiceMantenedorCliente.WebServiceMantenedorClienteSoap>, CapaGuiConsumoService.ServiceMantenedorCliente.WebServiceMantenedorClienteSoap {
        
        public WebServiceMantenedorClienteSoapClient() {
        }
        
        public WebServiceMantenedorClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarClienteService(CapaGuiConsumoService.ServiceMantenedorCliente.Cliente cliente) {
            base.Channel.insertarClienteService(cliente);
        }
        
        public System.Data.DataSet retornarClienteService() {
            return base.Channel.retornarClienteService();
        }
        
        public CapaGuiConsumoService.ServiceMantenedorCliente.Cliente retornaPosicionClienteService(int pos) {
            return base.Channel.retornaPosicionClienteService(pos);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorCliente.Cliente buscarClienteService(string rut) {
            return base.Channel.buscarClienteService(rut);
        }
        
        public void eliminarClienteService(string rut) {
            base.Channel.eliminarClienteService(rut);
        }
        
        public void actualizarClienteService(CapaGuiConsumoService.ServiceMantenedorCliente.Cliente cliente) {
            base.Channel.actualizarClienteService(cliente);
        }
    }
}
