//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGuiConsumoService.ServiceMantenedorSalidaProducto {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorSalidaProducto.WebServiceMantenedorSalidaProductoSoap")]
    public interface WebServiceMantenedorSalidaProductoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarSalidaProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarSalidaProductoService(CapaGuiConsumoService.ServiceMantenedorSalidaProducto.Salida_P salida_producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarSalidaProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarSalidaProductoService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionSalidaProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorSalidaProducto.Salida_P retornaPosicionSalidaProductoService(int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarSalidaProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorSalidaProducto.Salida_P buscarSalidaProductoService(string id_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarSalidaPorRutClienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorSalidaProducto.Salida_P buscarSalidaPorRutClienteService(string rut_cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarSalidaProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarSalidaProductoService(string id_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarSalidaProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarSalidaProductoService(CapaGuiConsumoService.ServiceMantenedorSalidaProducto.Salida_P salida_producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarSalidaYDetalleService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarSalidaYDetalleService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdSalidaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscarIdSalidaService(string id_salida);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Salida_P : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_salidaField;
        
        private System.DateTime fechaField;
        
        private string cliente_rutField;
        
        private string usuario_rutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_salida {
            get {
                return this.id_salidaField;
            }
            set {
                this.id_salidaField = value;
                this.RaisePropertyChanged("Id_salida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Cliente_rut {
            get {
                return this.cliente_rutField;
            }
            set {
                this.cliente_rutField = value;
                this.RaisePropertyChanged("Cliente_rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Usuario_rut {
            get {
                return this.usuario_rutField;
            }
            set {
                this.usuario_rutField = value;
                this.RaisePropertyChanged("Usuario_rut");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorSalidaProductoSoapChannel : CapaGuiConsumoService.ServiceMantenedorSalidaProducto.WebServiceMantenedorSalidaProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorSalidaProductoSoapClient : System.ServiceModel.ClientBase<CapaGuiConsumoService.ServiceMantenedorSalidaProducto.WebServiceMantenedorSalidaProductoSoap>, CapaGuiConsumoService.ServiceMantenedorSalidaProducto.WebServiceMantenedorSalidaProductoSoap {
        
        public WebServiceMantenedorSalidaProductoSoapClient() {
        }
        
        public WebServiceMantenedorSalidaProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorSalidaProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorSalidaProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorSalidaProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarSalidaProductoService(CapaGuiConsumoService.ServiceMantenedorSalidaProducto.Salida_P salida_producto) {
            base.Channel.insertarSalidaProductoService(salida_producto);
        }
        
        public System.Data.DataSet retornarSalidaProductoService() {
            return base.Channel.retornarSalidaProductoService();
        }
        
        public CapaGuiConsumoService.ServiceMantenedorSalidaProducto.Salida_P retornaPosicionSalidaProductoService(int pos) {
            return base.Channel.retornaPosicionSalidaProductoService(pos);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorSalidaProducto.Salida_P buscarSalidaProductoService(string id_salida) {
            return base.Channel.buscarSalidaProductoService(id_salida);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorSalidaProducto.Salida_P buscarSalidaPorRutClienteService(string rut_cliente) {
            return base.Channel.buscarSalidaPorRutClienteService(rut_cliente);
        }
        
        public void eliminarSalidaProductoService(string id_salida) {
            base.Channel.eliminarSalidaProductoService(id_salida);
        }
        
        public void actualizarSalidaProductoService(CapaGuiConsumoService.ServiceMantenedorSalidaProducto.Salida_P salida_producto) {
            base.Channel.actualizarSalidaProductoService(salida_producto);
        }
        
        public System.Data.DataSet retornarSalidaYDetalleService() {
            return base.Channel.retornarSalidaYDetalleService();
        }
        
        public System.Data.DataSet buscarIdSalidaService(string id_salida) {
            return base.Channel.buscarIdSalidaService(id_salida);
        }
    }
}
