//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGuiConsumoService.ServiceMantenedorUsuario {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorUsuario.WebServiceMantenedorUsuarioSoap")]
    public interface WebServiceMantenedorUsuarioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarUsuarioService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarUsuarioService(CapaGuiConsumoService.ServiceMantenedorUsuario.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarUsuarioService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarUsuarioService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionUsuarioService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorUsuario.Usuario retornaPosicionUsuarioService(int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarUsuarioService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorUsuario.Usuario buscarUsuarioService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarUsuarioService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarUsuarioService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarUsuarioService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarUsuarioService(CapaGuiConsumoService.ServiceMantenedorUsuario.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarRutUsuarioService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscarRutUsuarioService(string rut);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string nombreField;
        
        private string claveField;
        
        private string cargoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("Cargo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorUsuarioSoapChannel : CapaGuiConsumoService.ServiceMantenedorUsuario.WebServiceMantenedorUsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorUsuarioSoapClient : System.ServiceModel.ClientBase<CapaGuiConsumoService.ServiceMantenedorUsuario.WebServiceMantenedorUsuarioSoap>, CapaGuiConsumoService.ServiceMantenedorUsuario.WebServiceMantenedorUsuarioSoap {
        
        public WebServiceMantenedorUsuarioSoapClient() {
        }
        
        public WebServiceMantenedorUsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorUsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorUsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorUsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarUsuarioService(CapaGuiConsumoService.ServiceMantenedorUsuario.Usuario usuario) {
            base.Channel.insertarUsuarioService(usuario);
        }
        
        public System.Data.DataSet retornarUsuarioService() {
            return base.Channel.retornarUsuarioService();
        }
        
        public CapaGuiConsumoService.ServiceMantenedorUsuario.Usuario retornaPosicionUsuarioService(int pos) {
            return base.Channel.retornaPosicionUsuarioService(pos);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorUsuario.Usuario buscarUsuarioService(string rut) {
            return base.Channel.buscarUsuarioService(rut);
        }
        
        public void eliminarUsuarioService(string rut) {
            base.Channel.eliminarUsuarioService(rut);
        }
        
        public void actualizarUsuarioService(CapaGuiConsumoService.ServiceMantenedorUsuario.Usuario usuario) {
            base.Channel.actualizarUsuarioService(usuario);
        }
        
        public System.Data.DataSet buscarRutUsuarioService(string rut) {
            return base.Channel.buscarRutUsuarioService(rut);
        }
    }
}
