//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGuiConsumoService.ServiceMantenedorMarca {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorMarca.WebServiceMantenedorMarcaSoap")]
    public interface WebServiceMantenedorMarcaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarMarcaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarMarcaService(CapaGuiConsumoService.ServiceMantenedorMarca.Marca marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarMarcaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarMarcaService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionMarcaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorMarca.Marca retornaPosicionMarcaService(int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarMarcaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorMarca.Marca buscarMarcaService(string id_marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarMarcaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarMarcaService(string id_marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarMarcaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarMarcaService(CapaGuiConsumoService.ServiceMantenedorMarca.Marca marca);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Marca : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_marcaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_marca {
            get {
                return this.id_marcaField;
            }
            set {
                this.id_marcaField = value;
                this.RaisePropertyChanged("Id_marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorMarcaSoapChannel : CapaGuiConsumoService.ServiceMantenedorMarca.WebServiceMantenedorMarcaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorMarcaSoapClient : System.ServiceModel.ClientBase<CapaGuiConsumoService.ServiceMantenedorMarca.WebServiceMantenedorMarcaSoap>, CapaGuiConsumoService.ServiceMantenedorMarca.WebServiceMantenedorMarcaSoap {
        
        public WebServiceMantenedorMarcaSoapClient() {
        }
        
        public WebServiceMantenedorMarcaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorMarcaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorMarcaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorMarcaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarMarcaService(CapaGuiConsumoService.ServiceMantenedorMarca.Marca marca) {
            base.Channel.insertarMarcaService(marca);
        }
        
        public System.Data.DataSet retornarMarcaService() {
            return base.Channel.retornarMarcaService();
        }
        
        public CapaGuiConsumoService.ServiceMantenedorMarca.Marca retornaPosicionMarcaService(int pos) {
            return base.Channel.retornaPosicionMarcaService(pos);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorMarca.Marca buscarMarcaService(string id_marca) {
            return base.Channel.buscarMarcaService(id_marca);
        }
        
        public void eliminarMarcaService(string id_marca) {
            base.Channel.eliminarMarcaService(id_marca);
        }
        
        public void actualizarMarcaService(CapaGuiConsumoService.ServiceMantenedorMarca.Marca marca) {
            base.Channel.actualizarMarcaService(marca);
        }
    }
}
