//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGuiConsumoService.ServiceMantenedorDetalleIngreso {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorDetalleIngreso.WebServiceMantenedorDetIngresoSoap")]
    public interface WebServiceMantenedorDetIngresoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarDetalleIngresoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarDetalleIngresoProductoService(CapaGuiConsumoService.ServiceMantenedorDetalleIngreso.Det_Ingreso detalle_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarDetalleIngresoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarDetalleIngresoProductoService(string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionDetalleIngresoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorDetalleIngreso.Det_Ingreso retornaPosicionDetalleIngresoProductoService(int pos, string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarDetalleIngresoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorDetalleIngreso.Det_Ingreso buscarDetalleIngresoProductoService(string id_detalle_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarDetallePorIdIngresoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorDetalleIngreso.Det_Ingreso buscarDetallePorIdIngresoService(string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDetalleIngresoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarDetalleIngresoProductoService(string id_detalle_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarDetalleIngresoProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarDetalleIngresoProductoService(CapaGuiConsumoService.ServiceMantenedorDetalleIngreso.Det_Ingreso detalle_ingreso);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Det_Ingreso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_detalle_ingresoField;
        
        private int cantidadField;
        
        private int valor_totalField;
        
        private string ingreso_p_id_ingresoField;
        
        private string producto_codigoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_detalle_ingreso {
            get {
                return this.id_detalle_ingresoField;
            }
            set {
                this.id_detalle_ingresoField = value;
                this.RaisePropertyChanged("Id_detalle_ingreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Valor_total {
            get {
                return this.valor_totalField;
            }
            set {
                this.valor_totalField = value;
                this.RaisePropertyChanged("Valor_total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Ingreso_p_id_ingreso {
            get {
                return this.ingreso_p_id_ingresoField;
            }
            set {
                this.ingreso_p_id_ingresoField = value;
                this.RaisePropertyChanged("Ingreso_p_id_ingreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Producto_codigo {
            get {
                return this.producto_codigoField;
            }
            set {
                this.producto_codigoField = value;
                this.RaisePropertyChanged("Producto_codigo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorDetIngresoSoapChannel : CapaGuiConsumoService.ServiceMantenedorDetalleIngreso.WebServiceMantenedorDetIngresoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorDetIngresoSoapClient : System.ServiceModel.ClientBase<CapaGuiConsumoService.ServiceMantenedorDetalleIngreso.WebServiceMantenedorDetIngresoSoap>, CapaGuiConsumoService.ServiceMantenedorDetalleIngreso.WebServiceMantenedorDetIngresoSoap {
        
        public WebServiceMantenedorDetIngresoSoapClient() {
        }
        
        public WebServiceMantenedorDetIngresoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorDetIngresoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorDetIngresoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorDetIngresoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarDetalleIngresoProductoService(CapaGuiConsumoService.ServiceMantenedorDetalleIngreso.Det_Ingreso detalle_ingreso) {
            base.Channel.insertarDetalleIngresoProductoService(detalle_ingreso);
        }
        
        public System.Data.DataSet retornarDetalleIngresoProductoService(string id_ingreso) {
            return base.Channel.retornarDetalleIngresoProductoService(id_ingreso);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorDetalleIngreso.Det_Ingreso retornaPosicionDetalleIngresoProductoService(int pos, string id_ingreso) {
            return base.Channel.retornaPosicionDetalleIngresoProductoService(pos, id_ingreso);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorDetalleIngreso.Det_Ingreso buscarDetalleIngresoProductoService(string id_detalle_ingreso) {
            return base.Channel.buscarDetalleIngresoProductoService(id_detalle_ingreso);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorDetalleIngreso.Det_Ingreso buscarDetallePorIdIngresoService(string id_ingreso) {
            return base.Channel.buscarDetallePorIdIngresoService(id_ingreso);
        }
        
        public void eliminarDetalleIngresoProductoService(string id_detalle_ingreso) {
            base.Channel.eliminarDetalleIngresoProductoService(id_detalle_ingreso);
        }
        
        public void actualizarDetalleIngresoProductoService(CapaGuiConsumoService.ServiceMantenedorDetalleIngreso.Det_Ingreso detalle_ingreso) {
            base.Channel.actualizarDetalleIngresoProductoService(detalle_ingreso);
        }
    }
}
