//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGuiConsumoService.ServiceMantenedorDetalleSalida {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorDetalleSalida.WebServiceMantenedorDetSalidaSoap")]
    public interface WebServiceMantenedorDetSalidaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarDetalleSalidaProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarDetalleSalidaProductoService(CapaGuiConsumoService.ServiceMantenedorDetalleSalida.Det_Salida detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarDetalleSalidaProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarDetalleSalidaProductoService(string id_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarDetalleSalidaProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorDetalleSalida.Det_Salida buscarDetalleSalidaProductoService(string id_detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarDetallePorIdSalidaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorDetalleSalida.Det_Salida buscarDetallePorIdSalidaService(string id_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDetalleSalidaProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarDetalleSalidaProductoService(string id_detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarDetalleSalidaProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarDetalleSalidaProductoService(CapaGuiConsumoService.ServiceMantenedorDetalleSalida.Det_Salida detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionDetalleSalidaProductoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorDetalleSalida.Det_Salida retornaPosicionDetalleSalidaProductoService(int pos, string id_salida);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Det_Salida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_detalle_salidaField;
        
        private int cantidadField;
        
        private int valor_totalField;
        
        private string salida_p_id_salidaField;
        
        private string producto_codigoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_detalle_salida {
            get {
                return this.id_detalle_salidaField;
            }
            set {
                this.id_detalle_salidaField = value;
                this.RaisePropertyChanged("Id_detalle_salida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Valor_total {
            get {
                return this.valor_totalField;
            }
            set {
                this.valor_totalField = value;
                this.RaisePropertyChanged("Valor_total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Salida_p_id_salida {
            get {
                return this.salida_p_id_salidaField;
            }
            set {
                this.salida_p_id_salidaField = value;
                this.RaisePropertyChanged("Salida_p_id_salida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Producto_codigo {
            get {
                return this.producto_codigoField;
            }
            set {
                this.producto_codigoField = value;
                this.RaisePropertyChanged("Producto_codigo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorDetSalidaSoapChannel : CapaGuiConsumoService.ServiceMantenedorDetalleSalida.WebServiceMantenedorDetSalidaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorDetSalidaSoapClient : System.ServiceModel.ClientBase<CapaGuiConsumoService.ServiceMantenedorDetalleSalida.WebServiceMantenedorDetSalidaSoap>, CapaGuiConsumoService.ServiceMantenedorDetalleSalida.WebServiceMantenedorDetSalidaSoap {
        
        public WebServiceMantenedorDetSalidaSoapClient() {
        }
        
        public WebServiceMantenedorDetSalidaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorDetSalidaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorDetSalidaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorDetSalidaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarDetalleSalidaProductoService(CapaGuiConsumoService.ServiceMantenedorDetalleSalida.Det_Salida detalle_salida) {
            base.Channel.insertarDetalleSalidaProductoService(detalle_salida);
        }
        
        public System.Data.DataSet retornarDetalleSalidaProductoService(string id_salida) {
            return base.Channel.retornarDetalleSalidaProductoService(id_salida);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorDetalleSalida.Det_Salida buscarDetalleSalidaProductoService(string id_detalle_salida) {
            return base.Channel.buscarDetalleSalidaProductoService(id_detalle_salida);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorDetalleSalida.Det_Salida buscarDetallePorIdSalidaService(string id_salida) {
            return base.Channel.buscarDetallePorIdSalidaService(id_salida);
        }
        
        public void eliminarDetalleSalidaProductoService(string id_detalle_salida) {
            base.Channel.eliminarDetalleSalidaProductoService(id_detalle_salida);
        }
        
        public void actualizarDetalleSalidaProductoService(CapaGuiConsumoService.ServiceMantenedorDetalleSalida.Det_Salida detalle_salida) {
            base.Channel.actualizarDetalleSalidaProductoService(detalle_salida);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorDetalleSalida.Det_Salida retornaPosicionDetalleSalidaProductoService(int pos, string id_salida) {
            return base.Channel.retornaPosicionDetalleSalidaProductoService(pos, id_salida);
        }
    }
}
