//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGuiConsumoService.ServiceMantenedorProveedor {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorProveedor.WebServiceMantenedorProveedorSoap")]
    public interface WebServiceMantenedorProveedorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarProveedorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarProveedorService(CapaGuiConsumoService.ServiceMantenedorProveedor.Proveedor proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarProveedorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarProveedorService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionProveedorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorProveedor.Proveedor retornaPosicionProveedorService(int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarProveedorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGuiConsumoService.ServiceMantenedorProveedor.Proveedor buscarProveedorService(string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarProveedorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarProveedorService(string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarProveedorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarProveedorService(CapaGuiConsumoService.ServiceMantenedorProveedor.Proveedor proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarRolProveedorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscarRolProveedorService(string rol);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Proveedor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rolField;
        
        private string nombre_proveedorField;
        
        private string direccionField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("Rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre_proveedor {
            get {
                return this.nombre_proveedorField;
            }
            set {
                this.nombre_proveedorField = value;
                this.RaisePropertyChanged("Nombre_proveedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorProveedorSoapChannel : CapaGuiConsumoService.ServiceMantenedorProveedor.WebServiceMantenedorProveedorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorProveedorSoapClient : System.ServiceModel.ClientBase<CapaGuiConsumoService.ServiceMantenedorProveedor.WebServiceMantenedorProveedorSoap>, CapaGuiConsumoService.ServiceMantenedorProveedor.WebServiceMantenedorProveedorSoap {
        
        public WebServiceMantenedorProveedorSoapClient() {
        }
        
        public WebServiceMantenedorProveedorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorProveedorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorProveedorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorProveedorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarProveedorService(CapaGuiConsumoService.ServiceMantenedorProveedor.Proveedor proveedor) {
            base.Channel.insertarProveedorService(proveedor);
        }
        
        public System.Data.DataSet retornarProveedorService() {
            return base.Channel.retornarProveedorService();
        }
        
        public CapaGuiConsumoService.ServiceMantenedorProveedor.Proveedor retornaPosicionProveedorService(int pos) {
            return base.Channel.retornaPosicionProveedorService(pos);
        }
        
        public CapaGuiConsumoService.ServiceMantenedorProveedor.Proveedor buscarProveedorService(string rol) {
            return base.Channel.buscarProveedorService(rol);
        }
        
        public void eliminarProveedorService(string rol) {
            base.Channel.eliminarProveedorService(rol);
        }
        
        public void actualizarProveedorService(CapaGuiConsumoService.ServiceMantenedorProveedor.Proveedor proveedor) {
            base.Channel.actualizarProveedorService(proveedor);
        }
        
        public System.Data.DataSet buscarRolProveedorService(string rol) {
            return base.Channel.buscarRolProveedorService(rol);
        }
    }
}
